### ISSUE TITLE
Is port number allowed in the idp.domain field for identity assertion result?

### ISSUE THREAD

**Issue by soareschen** [rtcweb-wg/security-arch#42]
This issue was also discussed in w3c/webrtc-pc#1502.

Section 5.6.5. specifies that a valid IdP URL may have custom port number. In section 5.6.6., the assertion result contains an `idp` field with `domain` and `protocol` sub fields. Is the `domain` field for specifying domain name only, or is port number allowed there?

**Comment by fluffy** [comment]
We should make the point that certificate does not have the port. The port number can not be verified cryptographically. Can put port with : in domain name.

**Comment by bifurcation** [comment]
FROM IETF100: Yes, port number is allowed, but we will need to note that there is no way to distinguish cryptographically between different port numbers.

**Comment by hardie** [comment]
Note that this will require an editorial change to the description of how to construct the URL, which currently describes it as a domain name, rather than an authority.

**Comment by ekr** [comment]
@hardie: any chance you could propose some text here?

**Comment by hardie** [comment]
The cleanest thing to do here looks to me to reference the RFC 3986 definition of authority.  I can provide a PR for that but I want to note two things first:  that would technically mean both that a userinfo section of the authority would be permitted and that an IP address could be supplied rather than a domain name.  I think the IP address is okay, though it should be pretty rare, and I can't imagine anyone actually putting in userinfo.  If folks think that either of those is a problem, though, we'll need to reconstruct this rather than importing the RFC 3986 definition.

**Comment by ekr** [comment]
The IP address is OK.

Could we just prohibit the userinfo?

**Comment by hardie** [comment]
Unfortunately, the production in RFC 3986 is:

authority   = [ userinfo "@" ] host [ ":" port ]

So we can't do a straight import.  We could make the same point about it that we make about port, though, that it would not be reflected in the certificate.  

I think the chance of anyone using it is pretty unlikely, so I'm not sure it would be that useful to drop it. If we forbade the use of Basic Authentication for IdP domains, then it would make slightly more sense, but I also don't see a reason to do that (nobody much would do that and anyone who does has the infrastructure to support it).

**Comment by ekr** [comment]
Can you please produce a PR. It would help if it had some text about how it's not in the cert.
